<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
	</array>
	<key>name</key>
	<string>MVN PCS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#expression</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>comment.mvn</string>
		</dict>
		<key>delimiter</key>
		<dict>
			<key>match</key>
			<string>^\s*[&amp;#].*$</string>
			<key>name</key>
			<string>keyword.control.mvn</string>
		</dict>
		<key>expression</key>
		<dict>
			<key>name</key>
			<string>instruction.mvn</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#label</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimiter</string>
				</dict>
			</array>
		</dict>
		<key>invalid-parameter</key>
		<dict>
			<key>name</key>
			<string>invalid.illegal.mvn</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#invalid-parameter-value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invalid-parameter-label</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invalid-parameter-number</string>
				</dict>
			</array>
		</dict>
		<key>invalid-parameter-label</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s)(?&lt;=[&gt;&lt;$K+\-*/]\s|JP\s|JZ\s|JN\s|LV\s|LD\s|MM\s|SC\s|RS\s|HM\s|GD\s|PD\s|OS\s)\s*([&gt;&lt;$K+\-*/]|JP|JZ|JN|LV|LD|MM|SC|RS|HM|GD|PD|OS)(?=\s)</string>
			<key>name</key>
			<string>invalid.illegal.mvn</string>
		</dict>
		<key>invalid-parameter-number</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s)(?&lt;=[&gt;&lt;$K+\-*/]\s|JP\s|JZ\s|JN\s|LV\s|LD\s|MM\s|SC\s|RS\s|HM\s|GD\s|PD\s|OS\s)(?:(?:[ \t]*\b[\w-_]+\b[ \t]*){2,}|(?:[ \t]*\b[\w-_]+;.*))(?=;?.*)</string>
			<key>name</key>
			<string>invalid.illegal.mvn</string>
		</dict>
		<key>invalid-parameter-value</key>
		<dict>
			<key>match</key>
			<string>[^\s;]+(/[^\da-fA-F]+|/[\da-fA-F]{5,}|=[^\d]+|=\d{5,}|`\w{3,})\S*</string>
			<key>name</key>
			<string>invalid.illegal.mvn</string>
		</dict>
		<key>label</key>
		<dict>
			<key>match</key>
			<string>^\s*(?![&gt;&lt;$K+\-*/]\s|JP\s|JZ\s|JN\s|LV\s|LD\s|MM\s|SC\s|RS\s|HM\s|GD\s|PD\s|OS\s)(\b[\w\-_]+\b)</string>
			<key>name</key>
			<string>entity.name.tag.mvn</string>
		</dict>
		<key>labeled-instruction</key>
		<dict>
			<key>begin</key>
			<string>^\s*(?![&gt;&lt;$K+\-*/]\s|JP\s|JZ\s|JN\s|LV\s|LD\s|MM\s|SC\s|RS\s|HM\s|GD\s|PD\s|OS\s)(\b[\w\-_]+\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>labeled.instruction.mvn</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string></string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>operation</key>
		<dict>
			<key>match</key>
			<string>\s*([&gt;&lt;$K+\-*/]|JP|JZ|JN|LV|LD|MM|SC|RS|HM|GD|PD|OS)(?=\s)</string>
			<key>name</key>
			<string>entity.name.function.mvn</string>
		</dict>
		<key>parameter</key>
		<dict>
			<key>name</key>
			<string>parameter.mvn</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#invalid-parameter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter-value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter-label</string>
				</dict>
			</array>
		</dict>
		<key>parameter-label</key>
		<dict>
			<key>match</key>
			<string>(?![&gt;&lt;$K+\-*/]\s|JP\s|JZ\s|JN\s|LV\s|LD\s|MM\s|SC\s|RS\s|HM\s|GD\s|PD\s|OS\s)\s+(?!/|=|`)(\b[\w\-_]+\b)(?=\s*$|\s*;)</string>
			<key>name</key>
			<string>variable.parameter.mvn</string>
		</dict>
		<key>parameter-value</key>
		<dict>
			<key>match</key>
			<string>(/[\da-fA-F]{4}|=\d{1,4}|`\w{2})</string>
			<key>name</key>
			<string>constant.numeric.mvn</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mvn</string>
	<key>uuid</key>
	<string>cafaadf5-a855-4b06-8867-78a387d1b659</string>
</dict>
</plist>
