<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
	</array>
	<key>name</key>
	<string>MVN PCS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#expression</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=^|[ \t])(;).*$\n?</string>
			<key>name</key>
			<string>comment.mvn</string>
		</dict>
		<key>delimiter</key>
		<dict>
			<key>name</key>
			<string>delimiter.mvn</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#delimiter-value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimiter-label</string>
				</dict>
			</array>
		</dict>
		<key>delimiter-label</key>
		<dict>
			<key>begin</key>
			<string>^\s*([#])[ \t]</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.mvn</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>delimiter.label.mvn</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=#[ \t])\s*(?![&gt;&lt;$K+\-*/]\s|JP\s|JZ\s|JN\s|LV\s|LD\s|MM\s|SC\s|RS\s|HM\s|GD\s|PD\s|OS\s)(\b[\w\-_]+\b)</string>
					<key>name</key>
					<string>variable.parameter.mvn</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^ \t]</string>
					<key>name</key>
					<string>invalid.illegal.mvn</string>
				</dict>
			</array>
		</dict>
		<key>delimiter-value</key>
		<dict>
			<key>begin</key>
			<string>^\s*([@&amp;])[ \t]</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.mvn</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>delimiter.value.mvn</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter-value</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^ \t]</string>
					<key>name</key>
					<string>invalid.illegal.mvn</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>name</key>
			<string>invalid.illegal.mvn</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#labeled-instruction</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#instruction</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimiter</string>
				</dict>
			</array>
		</dict>
		<key>instruction</key>
		<dict>
			<key>begin</key>
			<string>(?:^|\s)([&gt;&lt;$K+\-*/]|JP|JZ|JN|LV|LD|MM|SC|RS|HM|GD|PD|OS)(?=\s|$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.mvn</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>instruction.mvn</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^ \t]</string>
					<key>name</key>
					<string>invalid.illegal.mvn</string>
				</dict>
			</array>
		</dict>
		<key>label</key>
		<dict>
			<key>match</key>
			<string>^\s*(?![&gt;&lt;$K+\-*/]\s|JP\s|JZ\s|JN\s|LV\s|LD\s|MM\s|SC\s|RS\s|HM\s|GD\s|PD\s|OS\s)(\b[\w\-_]+\b)</string>
			<key>name</key>
			<string>entity.name.tag.mvn</string>
		</dict>
		<key>labeled-instruction</key>
		<dict>
			<key>begin</key>
			<string>^\s*(?![&gt;&lt;$K+\-*/]\s|JP\s|JZ\s|JN\s|LV\s|LD\s|MM\s|SC\s|RS\s|HM\s|GD\s|PD\s|OS\s)(\b[\w\-_]+\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.mvn</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>labeled.instruction.mvn</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#instruction</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^ \t]</string>
					<key>name</key>
					<string>invalid.illegal.mvn</string>
				</dict>
			</array>
		</dict>
		<key>parameter</key>
		<dict>
			<key>name</key>
			<string>parameter.mvn</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter-value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter-label</string>
				</dict>
			</array>
		</dict>
		<key>parameter-label</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=[&gt;&lt;$K+\-*/]|JP|JZ|JN|LV|LD|MM|SC|RS|HM|GD|PD|OS)\s+(?![&gt;&lt;$K+\-*/]\s|JP\s|JZ\s|JN\s|LV\s|LD\s|MM\s|SC\s|RS\s|HM\s|GD\s|PD\s|OS\s)(\b[\w\-_]+\b)</string>
			<key>name</key>
			<string>variable.parameter.mvn</string>
		</dict>
		<key>parameter-value</key>
		<dict>
			<key>match</key>
			<string>(/[\da-fA-F]{1,4}|=\d{1,5}|`\w{1,2}|#[01]{1,16})</string>
			<key>name</key>
			<string>constant.numeric.mvn</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mvn</string>
	<key>uuid</key>
	<string>cafaadf5-a855-4b06-8867-78a387d1b659</string>
</dict>
</plist>
